image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - zazuko-gmbh.expressive-rdf-mapper

tasks:
  - command: mysql < example-database.sql
  - init: cd pipeline
    command: npm ci
  - command: make install_ontop
  - command: make sql
