image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - zazuko-gmbh.expressive-rdf-mapper
    - Zazuko.vscode-rdf-sketch

tasks:
  - name: mysql-data-load
    before: gp await-port 3306
    init: |
      mysql < example-database.sql
    command: |
      gp sync-done mysql-data-load
      mysql -e 'SHOW TABLES FROM exampledatabase'
  - name: convert
    init: make install_ontop
    command: |
      gp sync-await mysql-data-load
      make convert
      gp sync-done convert
  - name: pipeline
    before: cd pipeline
    init: npm ci
    command: |
      gp sync-await convert
      npm run pipeline-file
